/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.CarroDAO;
import DAO.ClienteDAO;
import MODEL.Carro;
import MODEL.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz
 */
public class TelaListaCliente extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TelaListaCliente
     */
    
    //listando dados da tabela
    public void listarComCpf(){
    
        ClienteDAO dao = new ClienteDAO();
    List<Cliente> lista = dao.getListaComCpf();
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Cliente c: lista){
        
        dados.addRow(new Object[]{
            c.getId_cliente(),
            c.getCpf(),
            c.getNome(),
            c.getRazao_social(),
            c.getEndereco(),
            c.getFone(),
                          
            
                
        });
    
    }
    
        
    
    }
        public void listarComCnpj(){
    
        ClienteDAO dao = new ClienteDAO();
    List<Cliente> lista = dao.getListaComCnpj();
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Cliente c: lista){
        
        dados.addRow(new Object[]{
            c.getId_cliente(),
            c.getCnpj(),
            c.getNome(),
            c.getRazao_social(),
            c.getEndereco(),
            c.getFone(),
                          
            
                
        });
    
    }
    
        
    
    }
    
    public TelaListaCliente() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeClientes = new javax.swing.JTable();
        comboTipo = new javax.swing.JComboBox<>();
        lblRazao2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCelularDados = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        lblRazao = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        lblTipoCli = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        lblRazao1 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tabelaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Razão social", "Endereço", "Fone"
            }
        ));
        tabelaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDeClientes);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Física", "Pessoa Jurídica" }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });

        lblRazao2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRazao2.setText("Fone:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");

        try {
            txtCelularDados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblRazao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRazao.setText("Razão social:");

        txtRazao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblTipoCli.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoCli.setText("CPF:");

        txtCpfCnpj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblRazao1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRazao1.setText("Endereço:");

        txtEndereco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton1.setText("Excluir");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("ID:");

        txtId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipoCli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRazao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRazao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRazao1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndereco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRazao2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCelularDados, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addGap(243, 243, 243))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTipoCli)
                                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazao)
                            .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazao1)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazao2)
                            .addComponent(txtCelularDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnEditar))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
     
    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
        
          if(comboTipo.getSelectedItem().equals("Pessoa Física")){
               
               //mudando nome da coluna da tabela e da label
        tabelaDeClientes.getColumnModel().getColumn(1).setHeaderValue("CPF");
        tabelaDeClientes.getTableHeader().resizeAndRepaint();
        lblTipoCli.setText("CPF:");
        txtRazao.setEnabled(false);
        listarComCpf();

        }else if(comboTipo.getSelectedItem().equals("Pessoa Jurídica")) {
         tabelaDeClientes.getColumnModel().getColumn(1).setHeaderValue("CNPJ");
         tabelaDeClientes.getTableHeader().resizeAndRepaint();
         lblTipoCli.setText("CNPJ:");
         
         listarComCnpj();

        }
        
        
        
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
          
        
        if(comboTipo.getSelectedItem().equals("Pessoa Física")){
               
               //mudando nome da coluna da tabela e da label
        tabelaDeClientes.getColumnModel().getColumn(1).setHeaderValue("CPF");
        tabelaDeClientes.getTableHeader().resizeAndRepaint();
        lblTipoCli.setText("CPF:");
        listarComCpf();

        }else if(comboTipo.getSelectedItem().equals("Pessoa Jurídica")) {
         tabelaDeClientes.getColumnModel().getColumn(1).setHeaderValue("CNPJ");
         tabelaDeClientes.getTableHeader().resizeAndRepaint();
         lblTipoCli.setText("CNPJ:");
         listarComCnpj();

        }
          
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        Cliente cli = new Cliente();
        cli.setId_cliente(Integer.parseInt(txtId.getText()));
        cli.setNome(txtNome.getText());
        cli.setEndereco(txtEndereco.getText());
        cli.setFone(txtCelularDados.getText());
        ClienteDAO dao = new ClienteDAO();
             if(comboTipo.getSelectedItem().equals("Pessoa Física")){
        cli.setCpf(txtCpfCnpj.getText());
        dao.alteraComCpf(cli);   
        
         }else if(comboTipo.getSelectedItem().equals("Pessoa Jurídica")){
             cli.setCnpj(txtCpfCnpj.getText());
             cli.setRazao_social(txtRazao.getText());
             dao.alteraComCnpj(cli);
         }
    }//GEN-LAST:event_btnEditarActionPerformed
             
    private void tabelaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeClientesMouseClicked
       
        if(comboTipo.getSelectedItem().equals("Pessoa Física")){
        txtId.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 0).toString());

    txtCpfCnpj.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 1).toString());
        txtNome.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 2).toString());
         txtEndereco.setText(tabelaDeClientes.getValueAt(tabelaDeClientes.
            getSelectedRow(), 4).toString());
    txtCelularDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes.
            getSelectedRow(), 5).toString());
        }else if(comboTipo.getSelectedItem().equals("Pessoa Jurídica")){
       
        
        txtId.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 0).toString());

    txtCpfCnpj.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 1).toString());
        txtNome.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 2).toString());
    txtRazao.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 3).toString());
    txtEndereco.setText(tabelaDeClientes.getValueAt(tabelaDeClientes.
            getSelectedRow(), 4).toString());
    txtCelularDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes.
            getSelectedRow(), 5).toString());
        }
        
    }//GEN-LAST:event_tabelaDeClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblRazao1;
    private javax.swing.JLabel lblRazao2;
    private javax.swing.JLabel lblTipoCli;
    private javax.swing.JTable tabelaDeClientes;
    private javax.swing.JFormattedTextField txtCelularDados;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRazao;
    // End of variables declaration//GEN-END:variables
}
