/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;


import DAO.CarroDAO;
import MODEL.Carro;
import VIEW.utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz
 */
public class telaAdminCarros extends javax.swing.JFrame {

    //listando dados da tabela
    public void listar(){
    
    CarroDAO dao = new CarroDAO();
    List<Carro> lista = dao.getLista();
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Carro c: lista){
        
        dados.addRow(new Object[]{
            c.getId_carro(),
            c.getChassi(),
            c.getPlaca(),
            c.getModelo(),
            c.getAno(),
            c.getCor(),
            c.getCilindrada(),
            c.getTipoCombustivel(),
            c.getValor_mensal(),
            c.getKm_atual(),
            c.getKm_troca(),
           
                
            
                
        });
    
    }
    
        
    
    }
    public telaAdminCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelDaTabelaClientes = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoDados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtChassis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKmAtual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboAno = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtKmRevisao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValorAluguel = new javax.swing.JTextField();
        btnPesquisaNomeDadosPessoais = new javax.swing.JButton();
        comboCilindrada = new javax.swing.JComboBox<>();
        comboCombustivel = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        painelConsultaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeClientes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtNomeConsultaCliente = new javax.swing.JTextField();
        btnPesquisaCliente = new javax.swing.JToggleButton();
        painelConsultaClientes1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNomeConsultaCliente1 = new javax.swing.JTextField();
        btnPesquisaCliente1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaDeClientes3 = new javax.swing.JTable();
        painelConsultaClientes2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtNomeConsultaCliente2 = new javax.swing.JTextField();
        btnPesquisaCliente2 = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaDeClientes4 = new javax.swing.JTable();
        btnSalvarCadCli = new javax.swing.JButton();
        btnNovoCadCli = new javax.swing.JButton();
        btnExcluirCadCli = new javax.swing.JButton();
        btnEditarCadCli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controle de veículos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Codigo: ");

        txtCodigoDados.setEditable(false);
        txtCodigoDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDadosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        txtModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModeloKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Cor:");

        txtCor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Placa:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Cilindrada:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Chassis:");

        txtChassis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtChassis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassisActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Quilometragel atual:");

        txtKmAtual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtKmAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmAtualActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Combustível:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Ano:");

        comboAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005" }));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Revisão:");

        txtKmRevisao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtKmRevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmRevisaoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Valor aluguel:");

        txtValorAluguel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValorAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorAluguelActionPerformed(evt);
            }
        });

        btnPesquisaNomeDadosPessoais.setText("Pesquisar");
        btnPesquisaNomeDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeDadosPessoaisActionPerformed(evt);
            }
        });

        comboCilindrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.3", "1.4", "1.5", "1.6", "1.8", "1.9", "2.0", "2.2", "2.4", "3.0", "3.3", "4.1" }));

        comboCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcóol", "Gasolina", "Flex", "Diesel" }));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Status:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Alugado", "Em manutenção" }));

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKmAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKmRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModelo))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(263, 263, 263)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisaNomeDadosPessoais))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaNomeDadosPessoais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKmAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKmRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        painelDaTabelaClientes.addTab("Detalhes do veículo", painelDadosPessoais);

        tabelaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Chassis", "Placa", "Modelo", "Ano", "Cor", "Cilindrada", "Combustível", "Valor mensal", "KM atual", "KM revisão", "Status"
            }
        ));
        tabelaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDeClientes);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Modelo:");

        txtNomeConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultaClienteActionPerformed(evt);
            }
        });
        txtNomeConsultaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeConsultaClienteKeyPressed(evt);
            }
        });

        btnPesquisaCliente.setText("Pesquisar");
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaClientesLayout = new javax.swing.GroupLayout(painelConsultaClientes);
        painelConsultaClientes.setLayout(painelConsultaClientesLayout);
        painelConsultaClientesLayout.setHorizontalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(869, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        painelConsultaClientesLayout.setVerticalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCliente)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDaTabelaClientes.addTab("Consulta geral de frota", painelConsultaClientes);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Modelo:");

        txtNomeConsultaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultaCliente1ActionPerformed(evt);
            }
        });
        txtNomeConsultaCliente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeConsultaCliente1KeyPressed(evt);
            }
        });

        btnPesquisaCliente1.setText("Pesquisar");
        btnPesquisaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCliente1ActionPerformed(evt);
            }
        });

        tabelaDeClientes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Modelo", "Placa", "Chassis", "Cor", "Cilindrada", "Combustível", "Ano", "KM atual", "KM revisão", "Valor mensal", "Status"
            }
        ));
        tabelaDeClientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeClientes3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaDeClientes3);

        javax.swing.GroupLayout painelConsultaClientes1Layout = new javax.swing.GroupLayout(painelConsultaClientes1);
        painelConsultaClientes1.setLayout(painelConsultaClientes1Layout);
        painelConsultaClientes1Layout.setHorizontalGroup(
            painelConsultaClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaClientes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsultaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(869, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelConsultaClientes1Layout.setVerticalGroup(
            painelConsultaClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaClientes1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelConsultaClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeConsultaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCliente1)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );

        painelDaTabelaClientes.addTab("Consulta disponibilidade de frota", painelConsultaClientes1);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Modelo:");

        txtNomeConsultaCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultaCliente2ActionPerformed(evt);
            }
        });
        txtNomeConsultaCliente2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeConsultaCliente2KeyPressed(evt);
            }
        });

        btnPesquisaCliente2.setText("Pesquisar");
        btnPesquisaCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCliente2ActionPerformed(evt);
            }
        });

        tabelaDeClientes4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Modelo", "Placa", "Chassis", "Cor", "Cilindrada", "Combustível", "Ano", "KM atual", "KM revisão", "Valor mensal", "Status"
            }
        ));
        tabelaDeClientes4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeClientes4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaDeClientes4);

        javax.swing.GroupLayout painelConsultaClientes2Layout = new javax.swing.GroupLayout(painelConsultaClientes2);
        painelConsultaClientes2.setLayout(painelConsultaClientes2Layout);
        painelConsultaClientes2Layout.setHorizontalGroup(
            painelConsultaClientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaClientes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsultaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(869, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelConsultaClientes2Layout.setVerticalGroup(
            painelConsultaClientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaClientes2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelConsultaClientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeConsultaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCliente2)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );

        painelDaTabelaClientes.addTab("Consulta revisão de frota", painelConsultaClientes2);

        btnSalvarCadCli.setText("SALVAR");
        btnSalvarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadCliActionPerformed(evt);
            }
        });

        btnNovoCadCli.setText("NOVO");
        btnNovoCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadCliActionPerformed(evt);
            }
        });

        btnExcluirCadCli.setText("EXCLUIR");
        btnExcluirCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadCliActionPerformed(evt);
            }
        });

        btnEditarCadCli.setText("EDITAR");
        btnEditarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDaTabelaClientes)
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(btnNovoCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnEditarCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCadCli)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(painelDaTabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCadCli)
                    .addComponent(btnExcluirCadCli)
                    .addComponent(btnSalvarCadCli)
                    .addComponent(btnNovoCadCli))
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(1400, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadCliActionPerformed
        // TODO add your handling code here:

        try {

            Carro obj = new Carro();
            obj.setChassi(txtChassis.getText());
            obj.setPlaca(txtPlaca.getText());
            obj.setModelo(txtModelo.getText());
            obj.setAno(comboAno.getSelectedItem().toString());
          
            obj.setCor(txtCor.getText());
            obj.setCilindrada(comboCilindrada.getSelectedItem().toString());
            obj.setTipoCombustivel(comboCombustivel.getSelectedItem().toString());
            obj.setValor_mensal(Double.parseDouble(txtValorAluguel.getText()));
            obj.setKm_atual(Integer.parseInt(txtKmAtual.getText()));
            obj.setKm_troca(Integer.parseInt(txtKmRevisao.getText()));
          
            
            CarroDAO dao = new CarroDAO();
            dao.adiciona(obj);
                        new utilitarios().LimpaTela(painelDadosPessoais);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }


    }//GEN-LAST:event_btnSalvarCadCliActionPerformed

    private void btnNovoCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoCadCliActionPerformed

    private void btnExcluirCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadCliActionPerformed
             /*   try {
                  Clientes obj = new Clientes();

                 obj.setId(Integer.parseInt(txtCodigoDados.getText()));
                      ClientesDAO dao = new ClientesDAO();
                      dao.excluirCliente(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

            
        } catch (Exception e) {
        }
*/
    }//GEN-LAST:event_btnExcluirCadCliActionPerformed

    private void btnEditarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadCliActionPerformed
        // TODO add your handling code here:
        
/*
        try {

            Clientes obj = new Clientes();
            obj.setNome(txtNomeDados.getText());
            obj.setRg(txtRgDados.getText());
            obj.setCpf(txtCpfDados.getText());
            obj.setEmail(txtEmailDados.getText());
            obj.setTelefone(txtTelefonedados.getText());
            obj.setCelular(txtCelularDados.getText());
            obj.setCep(txtCepDados.getText());
            obj.setEndereco(txtEnderecoDados.getText());
            obj.setNumero(Integer.parseInt(txtNumeroDados.getText()));
            obj.setComplemento(txtComplementoDados.getText());
            obj.setBairro(txtBairroDados.getText());
            obj.setCidade(txtCidadeDados.getText());
            obj.setUf(comboUfDados.getSelectedItem().toString());
            obj.setId(Integer.parseInt(txtCodigoDados.getText()));
            
            ClientesDAO dao = new ClientesDAO();
            dao.alterarCliente(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
        */
    }//GEN-LAST:event_btnEditarCadCliActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       ///caregar a lista
      listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        // Botao pesquisar na tabela de clientes

     /*
        String nome = "%"+txtNomeConsultaCliente.getText()+"%";
        ClientesDAO dao = new ClientesDAO();
        List<Clientes> lista = dao.buscaClientePorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
        dados.setNumRows(0);

        for(Clientes c: lista){

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()

            });
        }
        */
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void txtNomeConsultaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeConsultaClienteKeyPressed
        // Pesquisa enquanto digita
      /*
        String nome = "%"+txtNomeConsultaCliente.getText()+"%";
        ClientesDAO dao = new ClientesDAO();
        List<Clientes> lista = dao.buscaClientePorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
        dados.setNumRows(0);

        for(Clientes c: lista){

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()

            });
        }*/
    }//GEN-LAST:event_txtNomeConsultaClienteKeyPressed

    private void txtNomeConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaClienteActionPerformed

    private void tabelaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeClientesMouseClicked
        // passar dados da tabela para o painel de Dados Pessoais
     /*
        painelDaTabelaClientes.setSelectedIndex(0);
        txtCodigoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 0).toString());

    txtNomeDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 1).toString());
        txtRgDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 2).toString());
    txtCpfDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 3).toString());
        txtEmailDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 4).toString());
    txtTelefonedados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 5).toString());
        txtCelularDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 6).toString());
    txtCepDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 7).toString());
        txtEnderecoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 8).toString());
    txtNumeroDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 9).toString());
        txtComplementoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 10).toString());
    txtBairroDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 11).toString());
        txtCidadeDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
            .getSelectedRow(), 12).toString());
    comboUfDados.setSelectedItem(tabelaDeClientes.getValueAt(tabelaDeClientes
        .getSelectedRow(), 13).toString());
*/
    }//GEN-LAST:event_tabelaDeClientesMouseClicked

    private void btnPesquisaNomeDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeDadosPessoaisActionPerformed
        // Pesquisar na tela dados pessoais
     /*   try {
            String nome = txtNomeDados.getText();
            Clientes obj = new Clientes();
            ClientesDAO dao = new ClientesDAO();

            obj = dao.consultaPorNome(nome);
            if(obj.getNome() != null){
                txtCodigoDados.setText(String.valueOf(obj.getId()));

                txtNomeDados.setText(obj.getNome());
                txtRgDados.setText(obj.getRg());
                txtCpfDados.setText(obj.getCpf());
                txtEmailDados.setText(obj.getEmail());
                txtTelefonedados.setText(obj.getTelefone());
                txtCelularDados.setText(obj.getCelular());
                txtCepDados.setText(obj.getCep());
                txtEnderecoDados.setText(obj.getEndereco());
                txtNumeroDados.setText(Integer.toString(obj.getNumero()));
                txtComplementoDados.setText(obj.getComplemento());
                txtBairroDados.setText(obj.getBairro());
                txtCidadeDados.setText(obj.getCidade());
                comboUfDados.setSelectedItem(obj.getUf());
            }else{
                JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        */

    }//GEN-LAST:event_btnPesquisaNomeDadosPessoaisActionPerformed

    private void txtValorAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorAluguelActionPerformed

    private void txtKmRevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmRevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmRevisaoActionPerformed

    private void txtKmAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmAtualActionPerformed

    private void txtChassisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassisActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyPressed
      /*  if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String nome = txtNomeDados.getText();
                Clientes obj = new Clientes();
                ClientesDAO dao = new ClientesDAO();

                obj = dao.consultaPorNome(nome);
                if(obj.getNome() != null){
                    txtCodigoDados.setText(String.valueOf(obj.getId()));

                    txtNomeDados.setText(obj.getNome());
                    txtRgDados.setText(obj.getRg());
                    txtCpfDados.setText(obj.getCpf());
                    txtEmailDados.setText(obj.getEmail());
                    txtTelefonedados.setText(obj.getTelefone());
                    txtCelularDados.setText(obj.getCelular());
                    txtCepDados.setText(obj.getCep());
                    txtEnderecoDados.setText(obj.getEndereco());
                    txtNumeroDados.setText(Integer.toString(obj.getNumero()));
                    txtComplementoDados.setText(obj.getComplemento());
                    txtBairroDados.setText(obj.getBairro());
                    txtCidadeDados.setText(obj.getCidade());
                    comboUfDados.setSelectedItem(obj.getUf());
                }else{
                    JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }*/
    }//GEN-LAST:event_txtModeloKeyPressed

    private void txtCodigoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDadosActionPerformed

    private void txtNomeConsultaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultaCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaCliente1ActionPerformed

    private void txtNomeConsultaCliente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeConsultaCliente1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaCliente1KeyPressed

    private void btnPesquisaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaCliente1ActionPerformed

    private void txtNomeConsultaCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultaCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaCliente2ActionPerformed

    private void txtNomeConsultaCliente2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeConsultaCliente2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaCliente2KeyPressed

    private void btnPesquisaCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaCliente2ActionPerformed

    private void tabelaDeClientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeClientes3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDeClientes3MouseClicked

    private void tabelaDeClientes4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeClientes4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDeClientes4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAdminCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAdminCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAdminCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAdminCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAdminCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCadCli;
    private javax.swing.JButton btnExcluirCadCli;
    private javax.swing.JButton btnNovoCadCli;
    private javax.swing.JToggleButton btnPesquisaCliente;
    private javax.swing.JToggleButton btnPesquisaCliente1;
    private javax.swing.JToggleButton btnPesquisaCliente2;
    private javax.swing.JButton btnPesquisaNomeDadosPessoais;
    private javax.swing.JButton btnSalvarCadCli;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<String> comboCilindrada;
    private javax.swing.JComboBox<String> comboCombustivel;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel painelConsultaClientes;
    private javax.swing.JPanel painelConsultaClientes1;
    private javax.swing.JPanel painelConsultaClientes2;
    private javax.swing.JTabbedPane painelDaTabelaClientes;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JTable tabelaDeClientes;
    private javax.swing.JTable tabelaDeClientes3;
    private javax.swing.JTable tabelaDeClientes4;
    private javax.swing.JTextField txtChassis;
    private javax.swing.JTextField txtCodigoDados;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtKmAtual;
    private javax.swing.JTextField txtKmRevisao;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNomeConsultaCliente;
    private javax.swing.JTextField txtNomeConsultaCliente1;
    private javax.swing.JTextField txtNomeConsultaCliente2;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorAluguel;
    // End of variables declaration//GEN-END:variables
}
